MACOSX_SDK_VERSION:        # [osx and x86_64]
- '10.14'                  # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
- '10.14'                  # [osx and x86_64]
github_actions_labels:
- cirun-openstack-cpu-large
- cirun-openstack-cpu-2xlarge
